### ISSUE TITLE
Trying to reach zmic

### ISSUE THREAD

**Issue by realJoshByrnes** [zmic/znode#1]
Hi zmic,

We've been trying to reach out to you regarding some of the reverse engineering you did with the MSN Chat control.

Unfortunately the details we have for you appear to be out of date.

If you could reach out to @jyonxo (Sky) or myself (JD) on Discord, that would be much appreciated https://discord.gg/e4yQPpF6

You may close this issue.

**Comment by jyonxo** [comment]
Hi @zmic  yes we are trying to reach out to you, stop being so stubborn and talk to us <3 :) 

Just want to see how you are doing and it is a royal pain in the ass to reach you for some reason.

-- Sky

**Comment by realJoshByrnes** [comment]
Received reply from @zmic
